version: '3'

services:
#  mariadb:
#    image: mariadb
#    env_file: .env
#    build:
#      context: ./mariadb # build repo
#      args:
#        MARIADB_USER: ${MARIADB_USER}
#        MARIADB_U_PASS: ${MARIADB_U_PASS}
#        MARIADB_SP_USER: ${MARIADB_SP_USER}
#        MARIADB_ROOT_PASS: ${MARIADB_ROOT_PASS}
#        MARIADB_WP: ${MARIADB_WP}
#        MARIADB_HOSTNAME: ${MARIADB_HOSTNAME}
#    container_name: mariadb # give specified name instead of a default name
#    restart: on-failure # restart only if failed
#    volumes: #volume_name:/path/...
#      - mariadb:/var/lib/mysql
#    networks: #network name from which the service will be part of
#      - inception

  nginx:
    image: nginx
    build: ./nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_started

  wordpress:
    image: wordpress
    build: ./wordpress
    container_name: wordpress
    restart: on-failure
    env_file: .env
    environment:
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_U_PASS=${MARIADB_U_PASS}
      - MARIADB_SP_USER=${MARIADB_SP_USER}
      - MARIADB_ROOT_PASS=${MARIADB_ROOT_PASS}
      - MARIADB_WP=${MARIADB_WP}
      - MARIADB_HOSTNAME=${MARIADB_HOSTNAME}
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
#    depends_on:
#      mariadb:
#        condition: service_started

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/lduplain/data/mariadb
      o: bind
  wordpress:
    driver_opts:
      type: none
      device: /home/lduplain/data/wordpress
      o: bind
